logging: True
verbose: 1
debug: False
logdir: "AgentOccam-Trajectories_gpt-4o-2024-05-13-azure/gitlab/auto"
logname: "AgentOccam"
max_steps: 50
agent:
  type: "AgentOccam"
  others:
    max_steps: 50
    logname: "AgentOccam"
    logging: True
    verbose: 1
    debug: False
  actor:
    debug: 0
    verbose: 1
    number: 1
    model: "gpt-4o-2024-05-13-azure"
    documented_interaction_elements: ["url", "plan", "reason", "observation summary", "retained element ids", "observation highlight"]
    online_interaction_elements: []
    input: ["step", "objective", "previous plans", "interaction history", "current observation"]
    interaction_history:
      verbose: True
      type: ["text"]
      step_num: "all"
    current_observation:
      type: ["auto"]
      auto: True
    output: ["interaction history summary", "observation description", "reason", "action", "observation highlight"]
    planning_command: ["branch", "prune"]
    tips: True
    navigation_command: ["click", "type", "stop", "note", "go_back"]
    play: ["step", "objective", "previous plans", "observation description", "reason", "action"]
    trash: ["objective", "step", "url", "instruction", "online input", "response"]
  critic:
    mode: false
    debug: 0
    verbose: 1
    model: "gpt-4o-2024-05-13-azure"
    documented_interaction_elements: []
    online_interaction_elements: []
    character: "normal"
    input: ["objective", "previous plans", "interaction history", "step", "current observation"]
    interaction_history:
      verbose: True
      type: ["text"]
      step_num: "all"
    current_observation:
      type: ["text"]
    output: ["observation description", "mistakes"]
    trash: ["instruction", "online input", "response"]
  judge:
    mode: false
    debug: 0
    verbose: 1
    model: "gpt-4o-2024-05-13-azure"
    documented_interaction_elements: []
    online_interaction_elements: []
    strict: false
    input: ["objective", "previous plans", "interaction history", "step", "current observation", "action choices"]
    interaction_history:
      verbose: True
      type: ["text"]
      step_num: "all"
    current_observation:
      type: ["text"]
    output: ["plan progress assessment", "action assessment", "action selection"]
    trash: ["instruction", "online input", "response"]
env:
  fullpage: true
  prune: true
  max_browser_rows: 500
  relative_task_dir: "new_tasks/gitlab"
  headless: True
  task_ids: [40000, 40001, 40002, 40003, 40004, 40010, 40011, 40012, 40013, 40014, 40020, 40021, 40022, 40023, 40030, 40031, 40032, 40033, 40034, 40040, 40041, 40042, 40043, 40044, 40050, 40051, 40052, 40053, 40060, 40061, 40062, 40063, 40064, 40070, 40071, 40072, 40073, 40074, 40075, 40076, 40080, 40081, 40082, 40083, 40084, 40090, 40091, 40092, 40093, 40094, 40100, 40101, 40102, 40103, 40104, 40110, 40111, 40112, 40113, 40114, 40120, 40121, 40122, 40123, 40124, 40130, 40131, 40132, 40133, 40134, 40140, 40141, 40142, 40143, 40144, 40150, 40151, 40152, 40160, 40161, 40162, 40163, 40164, 40170, 40171, 40172, 40173, 40174, 40180, 40181, 40182, 40190, 40191, 40192, 40193, 40194, 40200, 40201, 40202, 40210, 40211, 40212, 40220, 40221, 40222, 40230, 40231, 40232, 40240, 40241, 40242, 40243, 40244, 40250, 40251, 40252, 40253, 40254, 40260, 40261, 40262, 40263, 40264, 40270, 40271, 40272, 40273]